//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: table.proto
namespace Table
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchReq")]
  public partial class MatchReq : global::ProtoBuf.IExtensible
  {
    public MatchReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchRsp")]
  public partial class MatchRsp : global::ProtoBuf.IExtensible
  {
    public MatchRsp() {}
    
    private int _err_no;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"err_no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int err_no
    {
      get { return _err_no; }
      set { _err_no = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchResult")]
  public partial class MatchResult : global::ProtoBuf.IExtensible
  {
    public MatchResult() {}
    
    private bool _i_am_red;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"i_am_red", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool i_am_red
    {
      get { return _i_am_red; }
      set { _i_am_red = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _lv;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _icon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadyReq")]
  public partial class ReadyReq : global::ProtoBuf.IExtensible
  {
    public ReadyReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadyRsp")]
  public partial class ReadyRsp : global::ProtoBuf.IExtensible
  {
    public ReadyRsp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadyNotify")]
  public partial class ReadyNotify : global::ProtoBuf.IExtensible
  {
    public ReadyNotify() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartNotify")]
  public partial class StartNotify : global::ProtoBuf.IExtensible
  {
    public StartNotify() {}
    
    private bool _is_red;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_red", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_red
    {
      get { return _is_red; }
      set { _is_red = value; }
    }
    private bool _is_first;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_first", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_first
    {
      get { return _is_first; }
      set { _is_first = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Move")]
  public partial class Move : global::ProtoBuf.IExtensible
  {
    public Move() {}
    
    private int _srow;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"srow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int srow
    {
      get { return _srow; }
      set { _srow = value; }
    }
    private int _scol;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"scol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int scol
    {
      get { return _scol; }
      set { _scol = value; }
    }
    private int _drow;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"drow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int drow
    {
      get { return _drow; }
      set { _drow = value; }
    }
    private int _dcol;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"dcol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dcol
    {
      get { return _dcol; }
      set { _dcol = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveReq")]
  public partial class MoveReq : global::ProtoBuf.IExtensible
  {
    public MoveReq() {}
    
    private Table.Move _move;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"move", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Table.Move move
    {
      get { return _move; }
      set { _move = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveRsp")]
  public partial class MoveRsp : global::ProtoBuf.IExtensible
  {
    public MoveRsp() {}
    
    private int _err_no;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"err_no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int err_no
    {
      get { return _err_no; }
      set { _err_no = value; }
    }
    private Table.Move _move = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"move", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Table.Move move
    {
      get { return _move; }
      set { _move = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveNotify")]
  public partial class MoveNotify : global::ProtoBuf.IExtensible
  {
    public MoveNotify() {}
    
    private Table.Move _move;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"move", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Table.Move move
    {
      get { return _move; }
      set { _move = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}